spring.application.name=PokeApi

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = pokeapi1302@gmail.com
spring.mail.password = tlwb ydwd dryf orfv
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

jwt.secret = gH8sK29sLqP0xZrT6mNvY8bA1cD3fGhJkL9pQ2rS4tU6wXyZ
jwt.expiration = 900000