spring.application.name=PokeApi

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = pokeapi1302@gmail.com
spring.mail.password = tlwb ydwd dryf orfv
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

jwt.secret = clave_super_secreta_muy_larga_123456789123456789
jwt.expiration = 900000